### ISSUE TITLE
Unknown ruleset element_type: ct helper

### ISSUE THREAD

**Issue by rohoog** [MikPisula/packet-simulator#1]
[ Fedora 38 - firewalld-1.3.4 ]

```
Traceback (most recent call last):
  File "~/.local/bin/packet-simulator", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/.local/lib/python3.11/site-packages/packet_simulator/__main__.py", line 68, in main
    firewall = Firewall(ruleset)
               ^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/packet_simulator/firewall.py", line 19, in __init__
    self.ruleset = self.parse_ruleset(ruleset)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/packet_simulator/firewall.py", line 72, in parse_ruleset
    raise Exception(f"Unknown ruleset element_type: {element_type}")
Exception: Unknown ruleset element_type: ct helper
```

**Comment by MikPisula** [comment]
Hello, thanks for reporting. Would you mind posting the output of the following commands?

```bash
# nft -j list ruleset
# ip -j route show table all 
# ip -j address
```

If necessary, feel free to redact any sensitive information like MAC/IP addresses.

**Comment by MikPisula** [comment]
The `ct helper` issue should be resolved, if you do happen to find another issue please report it as well :).
